title: Padio
description: Padio is an advanced radio bot for Discord voice channels that lets you enjoy a wide range of trending online radio stations with high-quality, seamless performance. Whether you're looking to set the mood for a gaming session or just relax with your favorite tunes, Padio has you covered.
theme: just-the-docs

url: https://sobhan-srza.github.io/padio/
repository: Sobhan-SRZA/Padio

permalink: pretty

defaults:
  - scope:
      path: "docs" 
      type: "pages"
    values:
      layout: "default"
